name: 'Build documentation'
description: 'Build documentation using Swifts docc'
author: 'Wesley de Groot <email+gha@wesleydegroot.nl>'

on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to push to'
        required: false
        default: 'documentation'
        type: string
      product:
        description: 'product name'
        required: false
        default: '__AUTO__'
        type: string
      iOS:
        description: 'Build for iOS?'
        required: true
        default: false
        type: boolean
      temppath:
        description: 'product name'
        required: false
        default: 'tmpdocs'
        type: string

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create folder for generated documentation
      shell: bash
      env:
        temppath: ${{ inputs.temppath }}
      run: |
        echo "${{ inputs.temppath }}, ${{ github.event.inputs.temppath }}, $temppath"
        mkdir ${{ github.event.inputs.temppath }}

    - name: Add docc plugin to Package.swift
      shell: bash
      run: |
        echo "package.dependencies.append(" >> package.swift
        echo "  .package(url: \"https://github.com/apple/swift-docc-plugin\", from: \"1.0.0\")" >> package.swift
        echo ")" >> Package.swift

    - name: Build Documentation (SPM)
      shell: bash
      if: ${{ github.event.inputs.iOS == false }}
      run: |
        swift package --allow-writing-to-directory ${{ github.event.inputs.temppath }} \
        generate-documentation \
        --target ${{ github.event.inputs.product }} \
        --disable-indexing \
        --output-path ${{ github.event.inputs.temppath }} \
        --transform-for-static-hosting \
        --hosting-base-path `basename ${{ github.repository }}`

    - name: Build Documentation (iOS)
      shell: bash
      if: ${{ github.event.inputs.iOS == true }}
      run: |
        xcodebuild docbuild -scheme ${{ github.event.inputs.product }} \
        -destination generic/platform=iOS \
        OTHER_DOCC_FLAGS="--transform-for-static-hosting --hosting-base-path `basename ${{ github.repository }}` --output-path ${{ github.event.inputs.temppath }}"

    - name: Init new repo in and add required files
      shell: bash
      run: |
        cd ${{ github.event.inputs.temppath }}
        git init -b ${{ github.event.inputs.branch }}
        DOCURL=`basename ${{ github.repository }}`
        echo "{\"meta\":{\"title\":\"$DOCURL Documentation\"}}" > theme-settings.json

        DOCURL=${DOCURL//-/_}
        echo "<script>window.location.href = 'documentation/$DOCURL/'.toLowerCase();</script>" > index.html
        echo "<script>window.location.href = 'documentation/$DOCURL/'.toLowerCase();</script>" > 404.html

    - name: Commit generated files
      shell: bash
      run: |
        git add -A .
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m 'deploy'

    - name: Push to repo
      shell: bash
      run: |
        git push \
        "https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git" \
        HEAD:${{ github.event.inputs.branch }} \
        --force

branding:
  icon: "upload-cloud"
  color: "blue"
